# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            eggsfordinner
tagline:          notes by Michael Fussell
url:              http://eggsfordinner.com
paginate:         1
baseurl:          /
author:
  name:           Mike Fussell
  url:            https://twitter.com/fussell
  email:          fussell@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/mfussell

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}